version: '3'
services:
  node-app:
    image: m0hamedkhalid/mynode

    depends_on:
      - mongo    
  mongo:
    image: mongo
    restart: always
    volumes:
      -  mongoose:/data/db 

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  nginx:
    image: nginx:stable-alpine
    volumes:
      - /var/jenkins_home/workspace/tt:/etc/nginx/conf.d
    ports:
    - "80:80"
    depends_on:
      - node-app 
volumes:
  mongoose:      
    
   
