version: '3'
services:
  node-app:
    image: m0hamedkhalid/mynode
    env_file:
      - ./.env
    depends_on:
      - mongo    
  mongo:
    image: mongo
    restart: always
    volumes:
      -  mongoose:/data/db 

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:

    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/    
  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - node-app 
volumes:
  mongoose:      
    
   