version: '3'
services:
  node-app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
  
    volumes:
      - ./src:/app/src:ro 
    environment:  
      - node_env=dev
