version: '3'
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - ./src/index.js:/app/src/index.js:ro   
    
  
   
    environment:  
      - node_env=dev
